# Generated by Django 5.2.7 on 2025-10-14 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Advertisement", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(max_length=60, unique=True)),
            ],
        ),
    ]
