# Generated by Django 5.2.7 on 2025-10-14 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Advertisement", "0002_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="ads", to="Advertisement.tag"
            ),
        ),
    ]
